do $$
declare
  actor_id uuid;
begin
  select id into actor_id from public.profiles order by created_at asc limit 1;

  if actor_id is null then
    raise notice 'Skipping guide backfill because no profile exists yet.';
    return;
  end if;

  insert into public.item_recipes (item_name, item_category, crafting_recipe, notes, created_by, updated_by)
  values
    ('Alchemical Base', 'Resources', 'Alchemy Table', 'Foundation ingredient for potion crafting.', actor_id, actor_id),
    ('Boar Tusks', 'Resources', 'Hunting boars', 'Specialty material from boars.', actor_id, actor_id),
    ('Bromeliad', 'Resources', 'Found in swamp biome', 'Exotic swamp plant resource.', actor_id, actor_id),
    ('Cane Sugar', 'Resources', 'Farming sugar cane', 'Sweet ingredient for recipes.', actor_id, actor_id),
    ('Clay Bottle', 'Resources', 'Alchemy Table from Clay', 'Container used in alchemy recipes.', actor_id, actor_id),
    ('Clay Pot', 'Resources', 'Smelting Furnace / Workbench', 'Crafted clay container material.', actor_id, actor_id),
    ('Coffee Beans', 'Resources', 'Loot from ships / trade', 'Coffee crafting ingredient.', actor_id, actor_id),
    ('Copper Pot', 'Resources', 'Workbench from Copper Ingot', 'Refined metal container.', actor_id, actor_id),
    ('Cornmeal', 'Resources', 'Millstone from Corn', 'Processed grain ingredient.', actor_id, actor_id),
    ('Crab Meat', 'Resources', 'Hunting crabs', 'Seafood crafting ingredient.', actor_id, actor_id),
    ('Crocodile Hide Piece', 'Resources', 'Hunting crocodiles', 'Durable hide material.', actor_id, actor_id),
    ('Crocodile Tail', 'Resources', 'Hunting crocodiles', 'Meat resource from crocodiles.', actor_id, actor_id),
    ('Dodo Egg', 'Resources', 'Dodo nests / hunting dodos', 'Egg ingredient for cooking.', actor_id, actor_id),
    ('Essence Arborum', 'Resources', 'Large Smelting Furnace', 'Magical late-game crafting material.', actor_id, actor_id),
    ('Fertile Soil', 'Resources', 'Foothills abandoned farms', 'Specialized farming resource.', actor_id, actor_id),
    ('Firefly', 'Resources', 'Caught at night', 'Luminous night resource.', actor_id, actor_id),
    ('Foothills Iron Ore', 'Resources', 'Mining in Foothills biome', 'Foothills-specific iron ore.', actor_id, actor_id),
    ('Healing Herbs', 'Resources', 'Gathering in the wild', 'Core potion ingredient.', actor_id, actor_id),
    ('Hewn Stone', 'Resources', 'Workbench from Stone', 'Processed stone building material.', actor_id, actor_id),
    ('Ingot Arborum', 'Resources', 'Enchanting Table', 'Advanced enchanted ingot.', actor_id, actor_id),
    ('Animal Fat', 'Resources', 'From animals', 'Lamp crafting ingredient.', actor_id, actor_id),
    ('Ironware', 'Resources', 'Workbench from Iron Ingot', 'Processed iron component.', actor_id, actor_id),
    ('Meat', 'Resources', 'Hunting animals', 'Common meat resource.', actor_id, actor_id),
    ('Millstone Parts', 'Resources', 'Crafted / found', 'Construction parts for Millstone.', actor_id, actor_id),
    ('Misty Orchid', 'Resources', 'Mid-tier islands', 'Rare flower resource.', actor_id, actor_id),
    ('Mountain Goat Horn', 'Resources', 'Hunting mountain goats', 'Mountain creature drop.', actor_id, actor_id),
    ('Nails', 'Resources', 'Workbench', 'Fastening material for construction.', actor_id, actor_id),
    ('Pearl', 'Resources', 'From scallop shells', 'Precious crafting resource.', actor_id, actor_id),
    ('Planks', 'Resources', 'Shipwreck debris', 'Scavenged plank material.', actor_id, actor_id),
    ('Salt', 'Resources', 'Ship cargo / harvesting', 'Seasoning and recipe material.', actor_id, actor_id),
    ('Sewing Tools', 'Resources', 'People of Tortuga vendor', 'Tailoring resource.', actor_id, actor_id),
    ('Sweet Potato', 'Resources', 'Found in jungle biome', 'Farm/cooking root vegetable.', actor_id, actor_id),
    ('Tear of Sorrow', 'Resources', 'Found in swamp biome', 'Rare mystical reagent.', actor_id, actor_id),
    ('Wolf Fang', 'Resources', 'Hunting wolves', 'Predator drop material.', actor_id, actor_id),
    ('Bacon and Eggs', 'Consumables', 'Cooking Fire', 'Uncommon food with vitality buff.', actor_id, actor_id),
    ('Banana', 'Consumables', 'Found on palm trees', 'Common raw fruit.', actor_id, actor_id),
    ('Banana Muffin', 'Consumables', 'Cooking Fire', 'Rare precision food.', actor_id, actor_id),
    ('Bean Soup', 'Consumables', 'Cooking Fire', 'Uncommon agility food.', actor_id, actor_id),
    ('Boiled Crab', 'Consumables', 'Cooking Fire', 'Uncommon crab meal.', actor_id, actor_id),
    ('Burrito', 'Consumables', 'Cooking Fire', 'Rare buff food.', actor_id, actor_id),
    ('Cayenne Pepper', 'Consumables', 'Gathered in the wild', 'Common spicy ingredient.', actor_id, actor_id),
    ('Chowder', 'Consumables', 'Cooking Fire', 'Rare agility food.', actor_id, actor_id),
    ('Coconut', 'Consumables', 'Harvested from palm trees', 'Common raw coconut.', actor_id, actor_id),
    ('Coconut Milk With Bananas', 'Consumables', 'Cooking Fire', 'Uncommon drink/buff food.', actor_id, actor_id),
    ('Coconut Soup', 'Consumables', 'Cooking Fire', 'Uncommon agility soup.', actor_id, actor_id),
    ('Cocoplum', 'Consumables', 'Found in coastal areas', 'Common raw food.', actor_id, actor_id),
    ('Coffee', 'Consumables', 'Cooking Fire', 'Epic consumable buff drink.', actor_id, actor_id),
    ('Crab Soup with Diced Tomatoes', 'Consumables', 'Cooking Fire', 'Uncommon agility soup.', actor_id, actor_id),
    ('Dodo Broth', 'Consumables', 'Cooking Fire', 'Uncommon broth consumable.', actor_id, actor_id),
    ('Fish and Tostones', 'Consumables', 'Cooking Fire', 'Rare vitality food.', actor_id, actor_id),
    ('Hearty Egg Broth', 'Consumables', 'Cooking Fire', 'Rare agility broth.', actor_id, actor_id),
    ('Lime', 'Consumables', 'Foothills biome', 'Common raw fruit.', actor_id, actor_id),
    ('Meat Salad', 'Consumables', 'Cooking Fire', 'Uncommon vitality meal.', actor_id, actor_id),
    ('Meat in Tangy Mushroom Sauce', 'Consumables', 'Cooking Fire', 'Rare strength food.', actor_id, actor_id),
    ('Nut Pie', 'Consumables', 'Cooking Fire', 'Uncommon precision food.', actor_id, actor_id),
    ('Pastechi', 'Consumables', 'Cooking Fire', 'Uncommon buff food.', actor_id, actor_id),
    ('Refreshing Nut Drink', 'Consumables', 'Cooking Fire', 'Rare buff drink.', actor_id, actor_id),
    ('Refreshing Tomato Juice', 'Consumables', 'Cooking Fire', 'Uncommon buff drink.', actor_id, actor_id),
    ('Seafood Skewer', 'Consumables', 'Cooking Fire', 'Uncommon strength skewer.', actor_id, actor_id),
    ('Skewered Meat', 'Consumables', 'Cooking Fire', 'Uncommon meat consumable.', actor_id, actor_id),
    ('Spicy "Chicken" with Sweet Potato', 'Consumables', 'Cooking Fire', 'Rare vitality food.', actor_id, actor_id),
    ('Spicy Breaded Kebab', 'Consumables', 'Cooking Fire', 'Rare strength food.', actor_id, actor_id),
    ('Spicy Skewered Crab', 'Consumables', 'Cooking Fire', 'Uncommon strength food.', actor_id, actor_id),
    ('Spicy Swamp Juice', 'Consumables', 'Cooking Fire', 'Rare buff drink.', actor_id, actor_id),
    ('Sweet Lime Juice', 'Consumables', 'Cooking Fire', 'Uncommon drink buff.', actor_id, actor_id),
    ('Taco', 'Consumables', 'Cooking Fire', 'Epic buff food.', actor_id, actor_id),
    ('Tamale', 'Consumables', 'Cooking Fire', 'Uncommon buff food.', actor_id, actor_id),
    ('Tangy Nut Roll', 'Consumables', 'Cooking Fire', 'Uncommon precision food.', actor_id, actor_id),
    ('Tomato', 'Consumables', 'Farm plots', 'Common crop consumable.', actor_id, actor_id),
    ('Tortilla', 'Consumables', 'Cooking Fire', 'Uncommon cornmeal food.', actor_id, actor_id),
    ('Armor and Clothing Workshop', 'Buildings & Structures', 'Crafting Station (Wood)', 'Station for crafting armor sets.', actor_id, actor_id),
    ('Bonfire', 'Buildings & Structures', 'Crafting Station (Wood)', 'Respawn anchor and comfort buff source.', actor_id, actor_id),
    ('Disassembly Bench', 'Buildings & Structures', 'Crafting Station', 'Salvages gear into base materials.', actor_id, actor_id),
    ('Enchanting Table', 'Buildings & Structures', 'Crafting Station', 'Tier 3 station for enchanted crafting.', actor_id, actor_id),
    ('Fast Travel Point', 'Buildings & Structures', 'Structure', 'Teleport node between unlocked points.', actor_id, actor_id),
    ('Floor-Standing Torch', 'Buildings & Structures', 'Lighting', 'Portable static light source.', actor_id, actor_id),
    ('Jewellery Table', 'Buildings & Structures', 'Crafting Station', 'Station for rings and accessories.', actor_id, actor_id),
    ('Large Smelting Furnace', 'Buildings & Structures', 'Crafting Station', 'Advanced furnace for top-tier ores.', actor_id, actor_id),
    ('Millstone', 'Buildings & Structures', 'Crafting Station', 'Grinds and mixes processed materials.', actor_id, actor_id),
    ('Shipwright''s Workshop', 'Buildings & Structures', 'Crafting Station', 'Builds and upgrades ships.', actor_id, actor_id),
    ('Tent', 'Buildings & Structures', 'Furniture', 'Portable temporary revival shelter.', actor_id, actor_id),
    ('Upgrading Station', 'Buildings & Structures', 'Crafting Station (Wood)', 'Ascends item stats and gear tiers.', actor_id, actor_id),
    ('Weaponsmith', 'Buildings & Structures', 'Crafting Station', 'Crafts melee and firearm weapons.', actor_id, actor_id),
    ('Wharf', 'Buildings & Structures', 'Ship Structure', 'Docking and ship cargo transfer structure.', actor_id, actor_id),
    ('Workbench', 'Buildings & Structures', 'Crafting Station (Wood)', 'Foundational station for starter crafting.', actor_id, actor_id),
    ('Iron Stomach', 'Talents', 'Talent point unlock', 'Extends active food buff duration.', actor_id, actor_id),
    ('Comfort Seeker', 'Talents', 'Talent point unlock', 'Extends the Rested buff duration.', actor_id, actor_id),
    ('Deep Breath', 'Talents', 'Talent point unlock', 'Increases underwater breath duration.', actor_id, actor_id),
    ('Night Owl', 'Talents', 'Talent point unlock', 'Increases stamina regeneration at night.', actor_id, actor_id),
    ('Green Thumb', 'Talents', 'Talent point unlock', 'Improves farm harvest yield.', actor_id, actor_id),
    ('Butcher', 'Talents', 'Talent point unlock', 'Chance to get extra animal harvest drops.', actor_id, actor_id),
    ('Forager', 'Talents', 'Talent point unlock', 'Improves wild flora gathering yields.', actor_id, actor_id),
    ('Angler', 'Talents', 'Talent point unlock', 'Improves fishing speed and catch handling.', actor_id, actor_id),
    ('Swashbuckler', 'Talents', 'Talent point unlock', 'Reduces stamina use with light one-hand attacks.', actor_id, actor_id),
    ('Heavy Handed', 'Talents', 'Talent point unlock', 'Increases heavy two-hand poise damage.', actor_id, actor_id),
    ('Perfect Deflection', 'Talents', 'Talent point unlock', 'Parries remove extra enemy poise.', actor_id, actor_id),
    ('Riposte', 'Talents', 'Talent point unlock', 'Boosts damage after a successful parry.', actor_id, actor_id),
    ('Rallying Strike', 'Talents', 'Talent point unlock', 'Improves rally healing conversion.', actor_id, actor_id),
    ('Fleet Footed', 'Talents', 'Talent point unlock', 'Reduces stamina cost of dodging.', actor_id, actor_id),
    ('Scattershot', 'Talents', 'Talent point unlock', 'Increases blunderbuss spread and stagger chance.', actor_id, actor_id),
    ('Shipwright''s Touch', 'Talents', 'Talent point unlock', 'Improves ship repair efficiency.', actor_id, actor_id),
    ('Sea Legs', 'Talents', 'Talent point unlock', 'Improves ship handling and sail transitions.', actor_id, actor_id),
    ('Wind Catcher', 'Talents', 'Talent point unlock', 'Increases top ship speed with tailwind.', actor_id, actor_id),
    ('Cannoneer', 'Talents', 'Talent point unlock', 'Improves cannon reload and projectile speed.', actor_id, actor_id),
    ('Boarding Party', 'Talents', 'Talent point unlock', 'Temporary mitigation buff after grappling ships.', actor_id, actor_id),
    ('Quartermaster', 'Talents', 'Talent point unlock', 'Improves hired NPC station throughput.', actor_id, actor_id),
    ('Master Chef', 'Talents', 'Talent point unlock', 'Chance to craft double food outputs.', actor_id, actor_id),
    ('Alchemist''s Touch', 'Talents', 'Talent point unlock', 'Chance to craft bonus potion/elixir.', actor_id, actor_id),
    ('Artisan', 'Talents', 'Talent point unlock', 'Reduces crafting time at major stations.', actor_id, actor_id),
    ('Scavenger', 'Talents', 'Talent point unlock', 'Chance for bonus loot and piastres from stashes.', actor_id, actor_id),
    ('Charismatic Trader', 'Talents', 'Talent point unlock', 'Reduces faction vendor prices.', actor_id, actor_id),
    ('Haggler', 'Talents', 'Talent point unlock', 'Improves sell value for traded cargo.', actor_id, actor_id),
    ('Shadow Step', 'Talents', 'Talent point unlock', 'Reduces crouch noise for stealth play.', actor_id, actor_id),
    ('Corruption', 'Status Effects', 'Corrupted/enchanted weapons', 'Stacking self-buff from specific weapons.', actor_id, actor_id),
    ('Distortion', 'Status Effects', 'Swamp Creature''s Tooth', 'Area debuff that disorients enemies.', actor_id, actor_id),
    ('Plague Marks', 'Status Effects', 'Rapier of Devastation', 'Stacking combat debuff on targets.', actor_id, actor_id),
    ('Rage', 'Status Effects', 'Executioner Halberd', 'Escalating crit chance self-buff.', actor_id, actor_id),
    ('Retaliation', 'Status Effects', 'Dueling Saber / Greatsword', 'Offensive buff after defensive timing windows.', actor_id, actor_id),
    ('Take Aim!', 'Status Effects', 'Cutlass', 'Stacking ranged-damage setup buff.', actor_id, actor_id),
    ('Ward', 'Status Effects', 'Executioner Halberd (Epic)', 'Defensive damage-reduction buff.', actor_id, actor_id),
    ('Conquistador''s Cuirass', 'Armor', 'Armor and Clothing Workshop', 'Heavy chest armor for tank set.', actor_id, actor_id),
    ('Conquistador''s Boots', 'Armor', 'Armor and Clothing Workshop', 'Heavy boots for tank set.', actor_id, actor_id),
    ('Flibustier''s Jacket', 'Armor', 'Armor and Clothing Workshop', 'Agile melee chest piece.', actor_id, actor_id),
    ('Flibustier''s Boots', 'Armor', 'Armor and Clothing Workshop', 'Agile melee boots.', actor_id, actor_id),
    ('Marksman''s Doublet', 'Armor', 'Armor and Clothing Workshop', 'Ranged set chest piece.', actor_id, actor_id),
    ('Marksman''s Boots', 'Armor', 'Armor and Clothing Workshop', 'Ranged set boots.', actor_id, actor_id),
    ('Pikeman''s Cuirass', 'Armor', 'Armor and Clothing Workshop', 'Two-handed set chest armor.', actor_id, actor_id),
    ('Pikeman''s Boots', 'Armor', 'Armor and Clothing Workshop', 'Two-handed set boots.', actor_id, actor_id),
    ('Privateer''s Doublet', 'Armor', 'Armor and Clothing Workshop', 'Critical-strike set chest piece.', actor_id, actor_id),
    ('Privateer''s Boots', 'Armor', 'Armor and Clothing Workshop', 'Critical-strike set boots.', actor_id, actor_id),
    ('Tracker''s Jacket', 'Armor', 'Armor and Clothing Workshop', 'Support/healing set chest piece.', actor_id, actor_id),
    ('Tracker''s Boots', 'Armor', 'Armor and Clothing Workshop', 'Support/healing set boots.', actor_id, actor_id),
    ('Survivor''s Bandana', 'Armor', 'Armor and Clothing Workshop', 'Uncommon early-game head armor.', actor_id, actor_id),
    ('Survivor''s Jacket', 'Armor', 'Armor and Clothing Workshop', 'Uncommon early-game chest armor.', actor_id, actor_id),
    ('Survivor''s Boots', 'Armor', 'Armor and Clothing Workshop', 'Uncommon early-game boots.', actor_id, actor_id),
    ('Headband', 'Armor', 'Armor and Clothing Workshop', 'Common starter head armor.', actor_id, actor_id),
    ('Torn Doublet', 'Armor', 'Armor and Clothing Workshop', 'Common starter chest armor.', actor_id, actor_id),
    ('Torn Boots', 'Armor', 'Armor and Clothing Workshop', 'Common starter boots.', actor_id, actor_id)
  on conflict ((lower(item_name)))
  do update set
    item_category = excluded.item_category,
    crafting_recipe = excluded.crafting_recipe,
    notes = excluded.notes,
    updated_by = excluded.updated_by,
    updated_at = now();
end
$$;
